create sequence MODULE_IDX_SEQ;

INSERT INTO MODULE (MODULE_IDX, MODULE_NAME, MODULE_ID, BROWSER_TITLE, SKIN, REG_DATE, LAYOUT_IDX, USE_THEME) VALUES ('MODUL000000000MODULE', 'module', 'module', '모듈', null, SYSDATE, null, 'Y');
