-- INSERT INTO MODULE (MODULE_IDX, MODULE_NAME, MODULE_ID, BROWSER_TITLE, SKIN, REG_DATE, LAYOUT_IDX, USE_THEME) VALUES ('MODUL00000000000TEST', 'test', 'test', '테스트', null, SYSDATE, null, 'Y');
--
-- INSERT INTO MODULE_OPTION(OPTION_NAME, OPTION_VALUE, OPTION_COMMENT, MODULE_IDX, MODULE_OPTION_SRL, ORDER_NUMBER) VALUES ('is_urgency', 'Y', '긴급 사용여부', 'MODUL00000000000TEST', MODULE_OPTION_SRL_SEQ.NEXTVAL, 1);
-- INSERT INTO MODULE_OPTION(OPTION_NAME, OPTION_VALUE, OPTION_COMMENT, MODULE_IDX, MODULE_OPTION_SRL, ORDER_NUMBER) VALUES ('is_anonymous', 'Y', '익명글 사용여부', 'MODUL00000000000TEST', MODULE_OPTION_SRL_SEQ.NEXTVAL, 2);
-- INSERT INTO MODULE_OPTION(OPTION_NAME, OPTION_VALUE, OPTION_COMMENT, MODULE_IDX, MODULE_OPTION_SRL, ORDER_NUMBER) VALUES ('is_category', 'Y', '분류 사용여부', 'MODUL00000000000TEST', MODULE_OPTION_SRL_SEQ.NEXTVAL, 3);
-- INSERT INTO MODULE_OPTION(OPTION_NAME, OPTION_VALUE, OPTION_COMMENT, MODULE_IDX, MODULE_OPTION_SRL, ORDER_NUMBER) VALUES ('is_reply', 'Y', '답글 사용여부', 'MODUL00000000000TEST', MODULE_OPTION_SRL_SEQ.NEXTVAL, 4);
-- INSERT INTO MODULE_OPTION(OPTION_NAME, OPTION_VALUE, OPTION_COMMENT, MODULE_IDX, MODULE_OPTION_SRL, ORDER_NUMBER) VALUES ('display_view', 'list', '목록 형태', 'MODUL00000000000TEST', MODULE_OPTION_SRL_SEQ.NEXTVAL, 5);

create sequence MODULE_IDX_SEQ;
